version: '3.1'
services:
  mongo:
    container_name: mwe_mongo
    image: mongo
    restart: always    
    ports:
      - 27077:27017
    volumes:
      - mwe_mongo_volume:/data/db
volumes:
  mwe_mongo_volume:
